services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama

    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ./ollama/data:/root/.ollama

    networks:
      - docker-local-lab

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui

    restart: unless-stopped

    ports:
      - "3000:8080"

    volumes:
      - ./openwebui/data:/app/backend/data

    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

    depends_on:
      - ollama

    networks:
      - docker-local-lab

  open-terminal:
    image: ghcr.io/open-webui/open-terminal:slim
    container_name: open-terminal

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - /home/ea/Desktop/Github:/workspace

    environment:
      - OPEN_TERMINAL_API_KEY=changeme

    networks:
      - docker-local-lab

networks:
  docker-local-lab:
    external: true
